# Generated by Django 5.2.5 on 2025-09-04 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rayon_contenir'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateFab',
            field=models.DateTimeField(default='2015-06-15 14:30:50'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='produit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='contient_produit', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayon',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='rayon_contient', to='monApp.rayon'),
        ),
    ]
