# Generated by Django 5.2.5 on 2025-09-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_produit_datefab_alter_contenir_produit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=200)),
            ],
        ),
    ]
