# Generated by Django 5.2.5 on 2025-09-04 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_status', to='monApp.status'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie_produits', to='monApp.categorie'),
        ),
    ]
