# Generated by Django 5.2.5 on 2025-09-04 08:09

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_produit_status_alter_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='dateFab',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
