# Generated by Django 5.2.5 on 2025-09-04 08:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_alter_produit_datefab'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatus', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatus', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('produit', 'rayon')},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='dateFab',
        ),
        migrations.AddField(
            model_name='produit',
            name='dateFabProd',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_produit', to='monApp.produit'),
        ),
        migrations.AlterField(
            model_name='contenir',
            name='rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenir_rayon', to='monApp.rayon'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_categorie', to='monApp.categorie'),
        ),
        migrations.AlterField(
            model_name='rayon',
            name='nomRayon',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='produit',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits_status', to='monApp.statut'),
        ),
        migrations.RemoveField(
            model_name='contenir',
            name='qte',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.AddField(
            model_name='contenir',
            name='Qte',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
